FctBundle\Entity\Alumnos:
    type: entity
    table: null
    repositoryClass: FctBundle\Repository\AlumnosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: 255
        apellido1:
            type: string
            length: 255
        apellido2:
            type: string
            length: 255
        ciclo:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToOne:
      empresas:
          targetEntity: Empresas
          inversedBy: alumno
          joinColumn:
              name: empresas_id
              referencedColumnName: id
      manyToOne:
        empresas:
            targetEntity: Profesores
            inversedBy: alumno
            joinColumn:
                name: profesores_id
                referencedColumnName: id
