# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FctBundle\Entity\Users: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: FctBundle:Users
        in_memory:
            memory:
              users:
                usuarios:
                  password: kitten
                  roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            http_basic: ~
        usuarios:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /usuarios/login
                check_path: /usuarios/login
                remember_me: true
            logout:
                path:   /usuarios/logout
                target: /usuarios/login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                always_remember_me: true
        main:
              anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
          - { path: ^/usuarios/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/usuarios/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/conf/, roles: ROLE_SUPER_ADMIN }
          - { path: ^/admin/, roles: ROLE_ADMIN }
          - { path: ^/, roles: ROLE_USER }
