fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }

fct_empresas:
    path:     /empresas/all
    defaults: { _controller: FctBundle:Empresas:all }

nueva_empresas:
    path:     /empresas/nueva
    defaults: { _controller: FctBundle:Empresas:nueva }

exito_empresas:
    path:     /empresas/msgExito
    defaults: { _controller: FctBundle:Empresas:msgExito }

show_alumnos:
    path:     /alumnos/show
    defaults: { _controller: FctBundle:Alumnos:show }

nuevo_alumnos:
    path:     /alumnos/nuevo
    defaults: { _controller: FctBundle:Alumnos:nuevo }

exito_alumnos:
    path:     /alumnos/msgExito
    defaults: { _controller: FctBundle:Alumnos:msgExito }

api_show:
    path:     /empresas
    defaults: { _controller: FctBundle:Api:empresa }
    methods:   [GET]

api_insert:
    path:     /empresas
    defaults: { _controller: FctBundle:Api:empresaInsert }
    methods:   [POST]

fct_profesores:
    path:     /profesores/all
    defaults: { _controller: FctBundle:Profesores:all }

new_profesores:
    path:     /profesores/nuevo
    defaults: { _controller: FctBundle:Profesores:new }

apiProfesores_show:
    path:     /profesores
    defaults: { _controller: FctBundle:Api:profesor }
    methods:   [GET]

register:
    path:     /usuarios/registro
    defaults: { _controller: FctBundle:Users:register }

login:
    path:     /usuarios/login
    defaults: { _controller: FctBundle:Users:login }

logout:
    path:     /usuarios/logout

admin_conf:
    path:     /admin/config
    defaults: { _controller: FctBundle:Users:admin }

admin_user:
    path:     /admin/user/{id}
    defaults: { _controller: FctBundle:Users:user }

admin_add:
    path:     /admin/user/{id}/add
    defaults: { _controller: FctBundle:Users:add }

admin_remove:
    path:     /admin/user/{id}/remove
    defaults: { _controller: FctBundle:Users:remove }
