fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }

fct_empresas:
    path:     /empresas/all
    defaults: { _controller: FctBundle:Empresas:all }

nueva_empresas:
    path:     /empresas/nueva
    defaults: { _controller: FctBundle:Empresas:nueva }

exito_empresas:
    path:     /empresas/msgExito
    defaults: { _controller: FctBundle:Empresas:msgExito }
